quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,https://main.d28kug95c4cgtc.amplifyapp.com

# configuration for the database connection
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.schema-management.strategy=update

# configuration for S3 image uploads
app.s3.bucket=${S3_BUCKET_NAME:}
app.s3.region=${APP_S3_REGION:us-east-1}
app.s3.public-base-url=${S3_PUBLIC_BASE_URL:}